### ISSUE TITLE
explorer 검색 결과 새로고침 문제

### ISSUE THREAD

**Issue by davidkwak** [amolabs/explorer2#13]
새로운 검색어로 검색해도 페이지 내용 변경이 되지 않음.

**Comment by Lbird** [comment]
How to reproduce:
- refresh the page
- input any search key and hit enter
- wait to see the search result
- input another search key and hit enter
- search result would not refresh

**Comment by Lbird** [comment]
resolved by 61067f642c379f8a2b74234ee242a3bcd66097e7
